language: php
cache: composer

php:
  - 5.6
  - 5.5
  - 5.4

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update

script:
  - rake build setEnv[testing] ci

notifications:
  email: true